### ISSUE TITLE
欢迎指正

### ISSUE THREAD

**Issue by reng99** [reng99/webpack#1]
如果大家对本webpack仓库有什么建议提出的话，请新建issue，或者在本issue下进行评论，自己定会改正。 :blush脸

**Comment by Wulawa** [comment]
你好，为什么总是先加载index.js 再执行common.js, 并且直接引handles文件 debugger 报错

**Comment by reng99** [comment]
你好 wulawa！common.js是整个站点的公用javascript文件存放点,index.js是首页用到的javascript文件的存放点，我是先加载了commom.js之后才引入index.js的啊。关于handlebars是需要引入handlebars-loader来解析的。
